language: python

cache:
  directories:
  - "~/.platformio"

install:
- ln -s $PWD /usr/local/share/arduino/libraries/Environment
- pip install -U platformio
- platformio lib install 986 # LSM303

env:
- BOARD=megaatmega2560

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
