language: python

cache:
  directories:
  - "~/.platformio"
  - "/Users/akkoyun/Documents/Arduino/libraries/Statistical"

install:
- pip install -U platformio
- platformio lib install 986 # LSM303

env:
- BOARD=megaatmega2560

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
