language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio lib install 986 # LSM303
- arduino --install-library "Statistical"

env:
- BOARD=megaatmega2560

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
